### ISSUE TITLE
Cannot pull circuit-driver when running against a private registry

### ISSUE THREAD

**Issue by fifthecho** [operable/go-relay#82]
Log output is 
```
8/28/2017 4:56:31 PMtime="2017-08-28T20:56:31Z" level=debug msg="Retrieving operable/circuit-driver:0.13 from upstream Docker registry."
8/28/2017 4:56:31 PMtime="2017-08-28T20:56:31Z" level=error msg="Error ocurred pulling image operable/circuit-driver: Error response from daemon: Get https://registry-1.docker.io/v2/operable/circuit-driver/manifests/0.13: unauthorized: incorrect username or password."
8/28/2017 4:56:31 PMtime="2017-08-28T20:56:31Z" level=error msg="Error response from daemon: Get https://registry-1.docker.io/v2/operable/circuit-driver/manifests/0.13: unauthorized: incorrect username or password"
```

I have a relay set up to pull from GitLab's registry for container images and as such it has the `RELAY_DOCKER_REGISTRY_EMAIL`, `RELAY_DOCKER_REGISTRY_HOST`, `RELAY_DOCKER_REGISTRY_PASSWORD`, and `RELAY_DOCKER_REGISTRY_USER` set as environment variables. However, this appears to be preventing the relay from pulling from `registry-1.docker.io` as it's trying to use the username and password from the GitLab registry.

If another relay has launched on this host and the circuit-driver container image is cached, then it launches fine.

**Comment by nmohoric** [comment]
Thanks for the report @fifthecho 
I've fixed this and it has been merged into the latest relay.
